import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'agentCode': 'Agent Code',
          'rememberMe': 'Remember me',
          'login': 'Login',
          'gpsCoordinates': 'GPS Coordinates',
          'thisIsLocationPointer':
              'This is a location pointer, and it known as mylocation',
          'singleAccuracy': 'Single\nAccuracy',
          'latitude': 'Latitude',
          'longitude': 'Longitude',
          'modifySchool': 'Modify School',
          'locationInfo': 'Location Info',
          'schoolsList': 'Schools List',
          'fillForm': 'Fill Form',
          'changeImage': 'Change Image',
          'schoolName': 'School name',
          'address': 'Address',
          'region': 'Region',
          'town': 'Town',
          'department': 'Department',
          'pleaseSelect': 'Please Select',
          'brick': 'brick',
          'straw': 'straw',
          'mix': 'mix',
          'Yes': 'Yes',
          'No': 'No',
          'electricity': 'Electricity',
          'water': 'Water',
          'internet': 'Internet',
          'toilet': 'Latrine',
          'description': 'Description',
          'addImages': 'Add Images',
          'submit': 'Submit',
          'status': 'Status',
          'date': 'Date',
          'editSchool': 'Edit School',
          'nextStep': 'Next Step',
          'noResponseFromServer': 'No response from server',
          'noInternetConnection': 'No internet connection',
          'photoLibrary': 'Photo Library',
          'camera': 'Camera',
          'thereIsNoInternetConnection':
              'There is no internet connection\nPlease check your internet connection',
          'tryAgain': 'Try again',
          'yourLocationHasBeenSubmitted':
              'Your location has\nbeen submitted successfully\nThank You!',
          'pleaseSelectAValidValue': 'Please Select a valid value',
          'fieldRequired': 'Field required',
          'areYouSureYou': 'Are you sure you want to exit?',
          'location': 'Location',
          'map': 'Map',
          'save': 'Save',
          'share': 'Share',
          'pending': 'Pending',
          'approved': 'Approved',
          'rejected': 'Rejected',
          'goToTheNextSchool': 'Go to the next school',
          'time': 'Time',
          'pleaseSelectAValidSchoolName': 'Please select a valid school name',
          'error': 'Error',
          'geoSchool': 'GeoSchool',
          'notModified': 'Not Modified',
          'connectionSpeed': 'Connection speed',
          'mobileNetwork': 'Mobile network',
          'fencing': 'Fencing',
          'constructionMaterial': 'Construction material',
          'totalStudents': 'Total students',
          'girls': 'Girls',
          'boys': 'Boys',
          'teachingStaff': 'Teaching staff',
          'library': 'Library',
          'computerRoom': 'Computer room',
          'phoneNumber': 'Phone number',
          'inactiveAccount':'Your account is inactive',
          'noSchool': 'No school available'
        },
        'fr_FR': {
          'agentCode': 'Code d\'agent',
          'rememberMe': 'Souviens-toi de moi',
          'login': 'Connexion',
          'gpsCoordinates': 'Coordonnées GPS',
          'thisIsLocationPointer':
              'Veuillez cliquer sur le bouton ci-dessous lorsque vous êtes prêt à géolocaliser une école',
          'singleAccuracy': 'Précision\ndu signal',
          'latitude': 'Latitude',
          'longitude': 'Longitude',
          'modifySchool': 'Modifier l\'école',
          'locationInfo': 'Informations sur votre position actuelle',
          'schoolsList': 'Liste des écoles',
          'fillForm': 'Veuilez remplir le formulaire ci-dessous',
          'changeImage': 'Modifier l\'image',
          'schoolName': 'Nom de l\'école',
          'address': 'Adresse',
          'region': 'Région',
          'town': 'Ville',
          'department': 'Département',
          'pleaseSelect': 'Veuillez sélectionner',
          'brick': 'En dur',
          'straw': 'Paillottes',
          'mix': 'Mixe',
          'Yes': 'Oui',
          'No': 'Non',
          'electricity': 'Électricité',
          'water': 'Eau',
          'internet': 'l\'Internet',
          'toilet': 'Latrine',
          'description': 'La description',
          'addImages': 'Ajouter des images',
          'submit': 'Soumettre',
          'status': 'Statut',
          'date': 'Date',
          'editSchool': 'Modifier l\'école',
          'nextStep': 'L\'étape suivante',
          'noResponseFromServer': 'Aucune réponse du serveur',
          'noInternetConnection': 'Pas de connexion Internet',
          'photoLibrary': 'Galerie de photos',
          'camera': 'Appareil photo',
          'thereIsNoInternetConnection':
              'Il n\'y a pas de connexion Internet\nVeuillez vérifier votre connexion Internet',
          'tryAgain': 'Essayer à nouveau',
          'yourLocationHasBeenSubmitted':
              'Votre position a\nété soumise avec succès!',
          'pleaseSelectAValidValue': 'Veuillez sélectionner une valeur valide',
          'fieldRequired': 'Champ obligatoire',
          'areYouSureYou': 'Êtes-vous sûr de vouloir quitter',
          'location': 'Emplacement',
          'map': 'Carte',
          'save': 'Sauvegarder',
          'share': 'Partager',
          'pending': 'En attente',
          'approved': 'Approuvée',
          'rejected': 'Rejetée',
          'goToTheNextSchool': 'Passer à l’école suivante',
          'time': 'Temps',
          'pleaseSelectAValidSchoolName':
              'Veuillez sélectionner un nom d\'école valide',
          'error': 'Erreur',
          'geoSchool': 'TrouveMonEcole',
          'notModified': 'Non modifié',
          'connectionSpeed': 'Débit connexion',
          'mobileNetwork': 'Réseau mobile',
          'fencing': 'Clôture',
          'constructionMaterial': 'Matériau construction',
          'totalStudents': 'Effectif total',
          'girls': 'Filles',
          'boys': 'Garçons',
          'teachingStaff': 'Effectif enseignant',
          'library': 'Bibliothèque',
          'computerRoom': 'Salle informatique',
          'phoneNumber': 'Numéro de téléphone',
          'inactiveAccount':'Votre compte est inactif',
          'noSchool':'Pas d’école disponible'
        },
      };
}
